version: '3.7'
services:
  mysql:
    image: mysql:8.1-oracle
    ports:
      - '3306:3306'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=no
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass